name: Release CLI

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: 'gradle'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.0.0"

      - name: Extract Version from from build.gradle
        run: |
          echo "version=$(gradle -q printVersion)" >> $GITHUB_ENV
          echo "java_version=$(gradle -q printJavaVersion)" >> $GITHUB_ENV
          echo "gradle_version=$(gradle -q printGradleVersion)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: gradle clean buildPlugin --no-daemon --no-build-cache --no-configuration-cache --no-parallel --no-watch-fs --max-workers=1

      - name: Ensure tag
        id: tag
        shell: bash
        run: |
          TAG="v${{ env.version }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          # 只读取远程 tag 索引
          git fetch --tags --force
          if git rev-parse "$TAG" >/dev/null 2>&1 || git ls-remote --tags origin "$TAG" | grep -q "$TAG"; then
            echo "Tag exists, skip creation"
          else
            git config user.email "github-actions@github.com"
            git config user.name "GitHub Actions"
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi
      - name: Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          generate_release_notes: true
          tag_name: ${{ steps.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite_files: true