name: Release CLI

on:
  workflow_dispatch:

jobs:
  native:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.0.0'
          install-dist: true
          build-cache-push: true
          build-cache-enabled: true
          arguments: build nativeCompile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack2server-artifacts
          path: |
            build/native/nativeCompile/pack2server*
            build/libs/*-cli.jar
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/native/nativeCompile/pack2server*
            build/libs/*-cli.jar
          generate_release_notes: true
          append_body: |
            ## Verification
            - **SBOM & provenance**: 见下方 attestations
            - **Checksums**: 已内置于 Release 文件
